const TOOLS_ID = {
  QUIZ_GENERATOR: '0',
  FLASHCARDS_GENERATOR: '1',
  WORKSHEET_GENERATOR: '2',
  SYLLABUS_GENERATOR: '6',
  AI_RESISTANCE_ASSIGNMENTS_GENERATOR: '8',
  RUBRIC_GENERATOR: '9',
  WRITING_FEEDBACK_GENERATOR: '7',
  PRESENTATION_GENERATOR: '10',
  LESSON_GENERATOR: '3',
  CONNECT_WITH_THEM: '4',
};

export { TOOLS_ID };
