const TOOLS_ID = {
  QUIZ_GENERATOR: '0',
  FLASHCARDS_GENERATOR: '1',
  WORKSHEET_GENERATOR: '2',
  SYLLABUS_GENERATOR: '6',
  AI_RESISTANCE_ASSIGNMENTS_GENERATOR: '8',
  RUBRIC_GENERATOR: '9',
  REWRITE_TEXT: '7',
  NOTES_GENERATOR: '10',
};

export { TOOLS_ID };
